server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?useSSL=false&serverTimezone=UTC
    username: root
    password: "010622"
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 1.15.145.217
    port: 6379
    password: "010622"
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: 12

